### ISSUE TITLE
Steam launch issue

### ISSUE THREAD

**Issue by zithorol** [FromDarkHell/BL3DX11Injection#6]
Just tried to install on steam today. When i try to launch the game it tried to open then immediately closes. So i tried laumching fron the exe in the win64 folder and it says " The code execution cannot proceed because d3d11_org.dll was not found"(a file named d3d11.dll is in the folder with the BL3 exe) . Reinstalling the program may fix this problem. not sure if this is because the recent update or just my missing something. though on install i followed the video step by step. thanks for any help you can provide
Windows 10 OS
i did install the vcredist(s) as well
also should note that the pluginloader does not open when the game fails to open. If i change the name of the d3d11.dll to d3d11_org.dll the game will launch but i have to manually open the hotfix merger and it stays on waiting for Borderlands3.exe

**Comment by FromDarkHell** [comment]
I would suggest checking if you've got a file named `d3d11.dll` in `C:/Windows/System32` (or whatever drive you've got Windows on) (Hit `d` on your keyboard a few times to get to it easily)
Should be something like this:
![DX11.dll](https://user-images.githubusercontent.com/9018764/105547665-57201d80-5cc4-11eb-9a80-9ce2977ffb13.png)
If you've got that file in `C:/Windows/System32`, then go to `Win64` of your BL3 install and send over `PluginLoader.log` if you've got it in `Win64`

> The Plugin Loader does not open when the game fails to open

The plugin loader *has* to work for the game to even launch, that's one of the few downsides, so its not going to launch when the game crashes (plus you won't see anything when you do it normally anyway)

> If I change the name of the `d3d11.dll` to `d3d11_org.dll` the game will launch

That's because you're effectively uninstalling the plugin loader when you do that, so its not going to crash when it doesn't load it :P

**Comment by zithorol** [comment]
sorry new to this...
I do have that file in my System32 folder....
do i need to send you the pluginloader.log?

**Comment by FromDarkHell** [comment]
Nevermind, I might've figured out the issue.
Try using this version of `d3d11.dll`, just extract out the contents into `Win64`.
[d3d11.zip](https://github.com/FromDarkHell/BL3DX11Injection/files/5859129/d3d11.zip)

**Comment by zithorol** [comment]
That seems to have solved the problem! Thanks for all the help. If you need me to try anything for you just let me know

**Comment by FromDarkHell** [comment]
This has been fixed with [v1.1.3](https://github.com/FromDarkHell/BL3DX11Injection/releases/tag/v1.1.3) and [this commit](https://github.com/FromDarkHell/BL3DX11Injection/commit/d4a66fdef60094f2c1e53e48e89f0b0a016bc0bc)

Thanks!
